package chess

const (
	WHITE = 0
	BLACK = 1
)

const (
	STARTING_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
)

const (
	WHITE_CASTLE_KINGSIDE  uint8 = 0b0001
	WHITE_CASTLE_QUEENSIDE uint8 = 0b0010
	WHITE_CASTLE_BOTH      uint8 = WHITE_CASTLE_KINGSIDE | WHITE_CASTLE_QUEENSIDE

	BLACK_CASTLE_KINGSIDE  uint8 = 0b0100
	BLACK_CASTLE_QUEENSIDE uint8 = 0b1000
	BLACK_CASTLE_BOTH      uint8 = BLACK_CASTLE_KINGSIDE | BLACK_CASTLE_QUEENSIDE
)
